name: LeetCode Sync

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python script.py

      - name: Commit and Push
        run: |
          git config --global user.name "Kunal Anand"
          git config --global user.email "kunalbhardwaj7222805@gmail.com"
          git add .
          git commit -m "Update LeetCode dashboard" || echo "No changes"
          git push
